---
# defaults file for base_dependencies
packages:
  # - python3
  - python3-pip
  - python3-venv
  # - python3-dev
  - supervisor
  - nginx
  - letsencrypt
  - python3-certbot-nginx
  # - git
  # - bash
  # - openssl
  - libssl-dev
  - libssl-doc
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python3-psycopg2